version: '3.8'

services:
  python_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: python_service
    ports:
      - "5001:5000"
    networks:
      - app_network
    volumes:
      - ./python_service:/app
    command: python app.py
  
  react_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: react_app
    ports:
      - "3000:3000"
    networks:
      - app_network  # Optional für lokale Entwicklung  

networks:
  app_network:
    driver: bridge
